scrape_configs:
- job_name: consul-primary-servers
  scrape_interval: 15s
  metrics_path: "/v1/agent/metrics"
  authorization: 
    credentials: 448eada4-df07-4633-8a17-d0ba7147cde4
  params:
    format: ['prometheus']
  static_configs:
  - targets:
    - consul-server${cluster_id}-primary-0:8500
    - consul-server${cluster_id}-primary-1:8500
    - consul-server${cluster_id}-primary-2:8500
    labels:
      dc: primary
      role: server
- job_name: consul-primary-clients
  scrape_interval: 15s
  metrics_path: "/v1/agent/metrics"
  authorization: 
    credentials: 448eada4-df07-4633-8a17-d0ba7147cde4
  params:
    format: ['prometheus']
  static_configs:
  - targets:
    - consul-primary-ui${cluster_id}:8500
    labels:
      dc: primary
      role: client

- job_name: consul-secondary-servers
  scrape_interval: 15s
  metrics_path: "/v1/agent/metrics"
  authorization: 
    credentials: 448eada4-df07-4633-8a17-d0ba7147cde4
  params:
    format: ['prometheus']
  static_configs:
  - targets:
    - consul-server${cluster_id}-secondary-0:8500
    - consul-server${cluster_id}-secondary-1:8500
    - consul-server${cluster_id}-secondary-2:8500
    labels:
      dc: secondary
      role: server
- job_name: consul-secondary-clients
  scrape_interval: 15s
  metrics_path: "/v1/agent/metrics"
  authorization: 
    credentials: 448eada4-df07-4633-8a17-d0ba7147cde4
  params:
    format: ['prometheus']
  static_configs:
  - targets:
    - consul-secondary-ui${cluster_id}:8500
    labels:
      dc: secondary
      role: client